import math
import random
import glm

#A customized Math library, all generated by ChatGPT

def transform_vector(v, q):
    qv = glm.vec3(q.x, q.y, q.z)
    retVal=glm.vec3(v)
    retVal+=2*glm.cross(qv, glm.cross(qv,v)+q.w*v)
    return retVal

def create_simple_view_proj(width, height):
    # 通过宽度和高度来创建一个正交投影矩阵
    
    matrix=[[ 2.0/width, 0.0, 0.0, 0.0 ],[ 0.0, 2.0/height, 0.0, 0.0 ], [ 0.0, 0.0, 1.0, 0.0 ],[ 0.0, 0.0, 1.0, 1.0 ],]
    matrix = glm.mat4(matrix)
    
    return matrix

def simple_ortho(window_width, window_height):
    # 创建一个正交投影矩阵
    return glm.ortho(0.0, window_width, 0.0, window_height, -1.0, 1.0)

def NearZero(num, rate=0.008):
    if glm.abs(num)< rate:
        return True
    return False

def Concatenate(q,p):
    retVal=glm.quat()
    qv=glm.vec3(q.x,q.y,q.z)
    pv=glm.vec3(p.x,p.y,p.z)
    newVec=p.w*qv+q.w*pv+glm.cross(pv,qv)
    retVal.x=newVec.x
    retVal.y=newVec.y
    retVal.z=newVec.z
    retVal.w=p.w*q.w-glm.dot(pv,qv)
    #retVal=glm.normalize(retVal)
    return retVal

def CreateLookAt(eye, target, up):
    zaxis=glm.normalize(target-eye)
    xaxis=glm.normalize(glm.cross(up, zaxis))
    yaxis=glm.normalize(glm.cross(zaxis, xaxis))
    trans=glm.vec3()
    trans.x=-glm.dot(xaxis, eye)
    trans.y=-glm.dot(yaxis, eye)
    trans.z=-glm.dot(zaxis, eye)
    
    temp=[
        [xaxis.x, yaxis.x, zaxis.x,0],
        [xaxis.y, yaxis.y, zaxis.y,0],
        [xaxis.z, yaxis.z, zaxis.z, 0],
        [trans.x, trans.y, trans.z, 1],
    ]
    return glm.mat4(temp)

def CreatePerspectiveFOV(fovY, width, height, near, far):
    yScale=glm.cot(fovY/2)
    xScale=yScale*height/width
    temp=[
        [xScale,0,0,0],
        [0,yScale, 0,0],
        [0,0, far/(far-near),1],
        [0,0,-near*far/(far-near),0]
    ]
    return glm.mat4(temp)

# 基类 Collider
class Collider:
    def __init__(self):
        self.mType = None  # 每个子类会设置自己的类型

    def CheckCollision(self, other):
        raise NotImplementedError("This method should be overridden in a subclass")

    def CheckCollisionWithRay(self, ray_origin, ray_dir, ray_length):
        raise NotImplementedError("This method should be overridden in a subclass")

# SphereCollider 类继承自 Collider
class SphereCollider(Collider):
    def __init__(self, center, radius):
        super().__init__()
        self.mType = 'Sphere'
        self.mCenter = center  # 球体的中心，使用glm.vec3表示
        self.mRadius = radius  # 球体的半径
        
    def CheckCollision(self, other):
        if other.mType == 'Sphere':
            return self.CheckCollisionWithSphere(other)
        elif other.mType == 'Box':
            return self.CheckCollisionWithBox(other)
        
    def CheckCollisionWithSphere(self, other):
        # 计算两个球体中心之间的距离
        distance = glm.length(self.mCenter - other.mCenter)
        # 如果两个球体的中心距离小于它们半径之和，则发生碰撞
        return distance < (self.mRadius + other.mRadius)
    
    def CheckCollisionWithBox(self, other):
        # 盒子碰撞检测逻辑，可以在这里添加
        pass
    
    def CheckCollisionWithRay(self, ray_origin, ray_dir, ray_length):
        # 计算从线段起点到球体中心的向量
        oc = ray_origin - self.mCenter
        a = glm.dot(ray_dir, ray_dir)
        b = 2.0 * glm.dot(oc, ray_dir)
        c = glm.dot(oc, oc) - self.mRadius * self.mRadius
        discriminant = b * b - 4.0 * a * c
        
        if discriminant < 0:
            return False  # 没有交点
        
        # 计算交点
        sqrt_discriminant = glm.sqrt(discriminant)
        t1 = (-b - sqrt_discriminant) / (2.0 * a)
        t2 = (-b + sqrt_discriminant) / (2.0 * a)

        # 只检测在射线的方向上（t > 0）并且在射线长度范围内的交点
        if t1 >= 0 and t1 <= ray_length:
            return True
        if t2 >= 0 and t2 <= ray_length:
            return True

        return False  # 没有交点

# BoxCollider 类继承自 Collider
class BoxCollider(Collider):
    def __init__(self, center, half_extents):
        super().__init__()
        self.mType = 'Box'
        self.mCenter = center  # 盒子的中心，使用 glm.vec3 表示
        self.mHalfExtents = half_extents  # 盒子的半宽、半高和半深度，使用 glm.vec3 表示
        
    def CheckCollision(self, other):
        if other.mType == 'Sphere':
            return self.CheckCollisionWithSphere(other)
        elif other.mType == 'Box':
            return self.CheckCollisionWithBox(other)

    def CheckCollisionWithBox(self, other):
        # 检查盒子是否重叠的AABB碰撞检测
        x_overlap = abs(self.mCenter.x - other.mCenter.x) <= (self.mHalfExtents.x + other.mHalfExtents.x)
        y_overlap = abs(self.mCenter.y - other.mCenter.y) <= (self.mHalfExtents.y + other.mHalfExtents.y)
        z_overlap = abs(self.mCenter.z - other.mCenter.z) <= (self.mHalfExtents.z + other.mHalfExtents.z)
        
        return x_overlap and y_overlap and z_overlap

    def CheckCollisionWithSphere(self, sphere):
        # 找出盒子和球体之间最近的点
        closest_point = glm.clamp(sphere.mCenter, 
                                  self.mCenter - self.mHalfExtents, 
                                  self.mCenter + self.mHalfExtents)
        
        # 计算这个点到球心的距离
        distance = glm.length(closest_point - sphere.mCenter)
        
        # 如果距离小于球体的半径，则发生碰撞
        return distance < sphere.mRadius
    
    def CheckCollisionWithRay(self, ray_origin, ray_dir, ray_length):
        tmin = -float('inf')
        tmax = float('inf')

        for i in range(3):  # X, Y, Z
            if glm.abs(ray_dir[i]) < 1e-6:  # 方向上没有变化
                if ray_origin[i] < self.mCenter[i] - self.mHalfExtents[i] or ray_origin[i] > self.mCenter[i] + self.mHalfExtents[i]:
                    return False  # 没有交点
            else:
                t1 = (self.mCenter[i] - self.mHalfExtents[i] - ray_origin[i]) / ray_dir[i]
                t2 = (self.mCenter[i] + self.mHalfExtents[i] - ray_origin[i]) / ray_dir[i]

                if t1 > t2:
                    t1, t2 = t2, t1

                tmin = max(tmin, t1)
                tmax = min(tmax, t2)

                if tmin > tmax:
                    return False  # 没有交点

        if tmin < 0 and tmax < 0:
            return False  # 完全在射线的负方向上

        if tmin > ray_length:
            return False  # 交点在射线长度外

        return True  # 有交点

    
def AngleBetweenVectors(v1, v2):
    # 计算点积
    dot_product = glm.dot(v1, v2)
    # 计算模长
    length_v1 = glm.length(v1)
    length_v2 = glm.length(v2)
    
    # 计算夹角（返回值在 -1 到 1 之间，所以用 acos 计算角度）
    cos_angle = dot_product / (length_v1 * length_v2)
    # 限制 cos_angle 在有效范围内，避免由于浮动误差导致值超过范围
    cos_angle = glm.clamp(cos_angle, -1.0, 1.0)
    angle = math.acos(cos_angle)  # 返回角度，单位为弧度
    
    return angle

def GenerateRandom2DDirection():
    return glm.normalize(glm.vec2(2*(random.random()-0.5), 2*(random.random()-0.5)))